/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error': '#490013',
        'error-container': '#a70138',
        'on-secondary-fixed-variant': '#006a2d',
        'on-tertiary-fixed-variant': '#563400',
        error: '#ff6e84',
        'on-primary-container': '#2e006c',
        'secondary-fixed': '#6bff8f',
        surface: '#0e0e13',
        'tertiary-fixed-dim': '#e79400',
        'on-surface-variant': '#acaab1',
        'primary-fixed': '#b28cff',
        'on-error-container': '#ffb2b9',
        'surface-container-lowest': '#000000',
        background: '#0e0e13',
        'on-secondary': '#005f28',
        secondary: '#6bff8f',
        'secondary-fixed-dim': '#5bf083',
        'on-secondary-container': '#e4ffe2',
        'primary-dim': '#8a4cfc',
        'inverse-surface': '#fcf8ff',
        primary: '#bd9dff',
        'on-tertiary-container': '#4a2c00',
        'inverse-primary': '#742fe5',
        'on-background': '#f9f5fd',
        'on-secondary-fixed': '#004a1d',
        'on-primary-fixed-variant': '#390083',
        'secondary-container': '#006e2f',
        'surface-variant': '#25252d',
        'surface-container-low': '#131319',
        'tertiary-dim': '#e79400',
        'on-primary-fixed': '#000000',
        'error-dim': '#d73357',
        'surface-bright': '#2c2b33',
        'tertiary-container': '#f8a010',
        'inverse-on-surface': '#55545b',
        'on-primary': '#3c0089',
        'primary-fixed-dim': '#a67aff',
        'on-tertiary-fixed': '#2a1700',
        'surface-tint': '#bd9dff',
        'on-surface': '#f9f5fd',
        'tertiary-fixed': '#f8a010',
        'secondary-dim': '#5bf083',
        'surface-container-highest': '#25252d',
        'surface-dim': '#0e0e13',
        tertiary: '#ffb148',
        'on-tertiary': '#573500',
        outline: '#76747b',
        'surface-container': '#19191f',
        'outline-variant': '#48474d',
        'surface-container-high': '#1f1f26',
        'primary-container': '#b28cff',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans'],
        body: ['Inter'],
        label: ['Inter'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}

